// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9T3dkHsH2LyLjAbpkfmag_luFwKG-0SI',
    appId: '1:1028422653014:web:a50c601ba7b3180bc457f7',
    messagingSenderId: '1028422653014',
    projectId: 'mob1-a3551',
    authDomain: 'mob1-a3551.firebaseapp.com',
    storageBucket: 'mob1-a3551.appspot.com',
    measurementId: 'G-9G6PGPR6RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs4tCP2q7Lo9lgZp2hn-X0-aQt_dtoqRE',
    appId: '1:1028422653014:android:ac45c3b2e60d963dc457f7',
    messagingSenderId: '1028422653014',
    projectId: 'mob1-a3551',
    storageBucket: 'mob1-a3551.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnE9tO8MfbNu3gBAUhe_wUpVwDJCW0m6g',
    appId: '1:1028422653014:ios:cdf2a852aa8729f1c457f7',
    messagingSenderId: '1028422653014',
    projectId: 'mob1-a3551',
    storageBucket: 'mob1-a3551.appspot.com',
    iosClientId: '1028422653014-kjfcreulmimj3nb7ftlbj60rqcdhcai5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobr1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnE9tO8MfbNu3gBAUhe_wUpVwDJCW0m6g',
    appId: '1:1028422653014:ios:1f588b2531eb1767c457f7',
    messagingSenderId: '1028422653014',
    projectId: 'mob1-a3551',
    storageBucket: 'mob1-a3551.appspot.com',
    iosClientId: '1028422653014-5kftol8eqi5mecnq9507bm3qm75p9rmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobr1.RunnerTests',
  );
}
